#!/usr/bin/env bash
#Script transfers a file from our client to a server

# Check if all parameters are provided
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

File_path=$1
Server_ip=$2
Username=$3
SSH_key=$4

# Transfer file using scp
scp -o StrictHostKeyChecking=no -i "$SSH_key" "$File_path" "$Username@$Server_ip:~/"

exit 0
