#!/usr/bin/env bash
# Script configures a new Ubuintu machine to respect above requirements

apt-get update
apt-get install -y nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
#Nginx to listen on port 80 and serve files from the /etc/nginx/html directory
printf %s "server {
     listen      80;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx restart
