#!/usr/bin/env bash
# SSH Config File
#
Host *
	User ubuntu
	PasswordAuthentication no
	IdentityFile ~/.ssh/school
	SendEnv LANG LC_*
	HashKnownHosts yes
	GSSAPIAuthentication yes
	GSSAPIDelegateCredentials no
